/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppLoansTrackingRouteImport } from './routes/_app.loans.tracking'
import { Route as AppLoansApplyRouteImport } from './routes/_app.loans.apply'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansTrackingRoute = AppLoansTrackingRouteImport.update({
  id: '/loans/tracking',
  path: '/loans/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansApplyRoute = AppLoansApplyRouteImport.update({
  id: '/loans/apply',
  path: '/loans/apply',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/payments': typeof AppPaymentsRoute
  '/profile': typeof AppProfileRoute
  '/loans/apply': typeof AppLoansApplyRoute
  '/loans/tracking': typeof AppLoansTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/payments': typeof AppPaymentsRoute
  '/profile': typeof AppProfileRoute
  '/loans/apply': typeof AppLoansApplyRoute
  '/loans/tracking': typeof AppLoansTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/loans/apply': typeof AppLoansApplyRoute
  '/_app/loans/tracking': typeof AppLoansTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/admin'
    | '/dashboard'
    | '/payments'
    | '/profile'
    | '/loans/apply'
    | '/loans/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/admin'
    | '/dashboard'
    | '/payments'
    | '/profile'
    | '/loans/apply'
    | '/loans/tracking'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/payments'
    | '/_app/profile'
    | '/_app/loans/apply'
    | '/_app/loans/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/tracking': {
      id: '/_app/loans/tracking'
      path: '/loans/tracking'
      fullPath: '/loans/tracking'
      preLoaderRoute: typeof AppLoansTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/apply': {
      id: '/_app/loans/apply'
      path: '/loans/apply'
      fullPath: '/loans/apply'
      preLoaderRoute: typeof AppLoansApplyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppLoansApplyRoute: typeof AppLoansApplyRoute
  AppLoansTrackingRoute: typeof AppLoansTrackingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppLoansApplyRoute: AppLoansApplyRoute,
  AppLoansTrackingRoute: AppLoansTrackingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
